services:
  nginx:
    image: nginx:latest
    container_name: grocery-nginx
    depends_on:
      - grocery
  redis:
    image: redis:latest
    container_name: grocery-redis
  mongodb:
    image: mongo:latest
    container_name: grocery-mongo
    environment:
      MONGO_INITDB_DATABASE: grocery
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
#    secrets:
#      - mongo_password
#    networks:
#      - backend
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: grocery-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: grocery-kafka
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
#  elastic:
#    image: elasticsearch:latest
#    container_name: grocery-elastic
  grocery:
    container_name: grocery-springboot
    image: grocery-springboot
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    environment:
      spring.profiles.active: "docker"
    ports:
      - "8080:8080"
    depends_on:
      - broker
      - mongodb
      - redis

volumes:
  mongodb_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:

#secrets:
#  - mongo_password:
#      file: ./secrets/mongo_password

networks:
  backend:
  payment: